### ISSUE TITLE
Share the dataset spliting

### ISSUE THREAD

**Issue by veya2ztn** [senli1073/SeisT#1]
Hi, do you plan share the dataset spliting(TRAIN/DEV/TEST) about the 277,000 samples from DiTing?
From the code, I guess it is the  `DiTing330km_light.csv` file?

**Comment by senli1073** [comment]
Hi @veya2ztn, 
Thank you for your attention to our work. We would be happy to provide the index numbers for the DiTing dataset used in the paper if you have obtained the necessary authorization for the DiTing dataset. You can also contact us via email: senli.1073@gmail.com
