### ISSUE TITLE
Bug: Incorrect Line Order in SeisT/training/preprocess.py

### ISSUE THREAD

**Issue by ZhouHao-commits** [senli1073/SeisT#3]
There appears to be an issue in the file SeisT/training/preprocess.py. Specifically, the lines at line 484 and line 491 are reversed, which may lead to contrary behavior during preprocessing.

**Comment by senli1073** [comment]
Thank you for pointing out this issue. I found that it does exist, but fortunately this part of the code lines has not been used before. I'll fix this bug later.

-- Sen

**Comment by senli1073** [comment]
@ZhouHao-commits I've fixed the bug and will close this issue.
